### PR TITLE
fix: update to terraform-plugin-sdk v2.34.0

### PR DESCRIPTION
**Pull request by spikecurtis**
Speculative fix in relation to https://github.com/coder/coder/issues/14726

There have been several issues fixed in the plugin-sdk and its dependencies about go routines and the RPC protocol. Since our `coder` plugin is itself very, very simple in design (it generally just reads data from environment variables for data sources, and just does validation on resources), it's hard to imagine a hang in our provider schema code (not impossible tho). The error reports we've seen all show the Coder provider as the one that is involved in `text file busy`, so it seems likely that it's something unique about the `coder/coder` provider.

`hashicorp/kubernetes` is used by both customers who reported the `text file busy` error, and it is on SDK version 2.29+ and we were back on 2.20 before this PR.

### CODE REVIEW

**Comment by spikecurtis** [comment]
* **#290** <a href="https://app.graphite.dev/github/pr/coder/terraform-provider-coder/290?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spikecurtis and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by johnstcn — APPROVED** [review]
v2.24.1 fixes some goroutine leaks, maybe related?
In any case, 👍

**Comment by spikecurtis** [comment]
### Merge activity

* **Sep 24, 7:56 AM EDT**: @spikecurtis started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/coder/terraform-provider-coder/290).

**Comment by matifali** [comment]
@spikecurtis we can patch the 1.0 after cherry picking this change into `release/1.0` branch.

**Pull request merged**
