### PR TITLE
chore(docs): move coder_parameter example

### PR DESCRIPTION
**Pull request by stirby**
The `coder_parameter` **data-source**'s code example was in the **resources** directory by mistake, moved.

Fixes https://github.com/coder/terraform-provider-coder/issues/242.

---

Curious what the failed `examples_test.go` looks like so intentionally ignored.

### CODE REVIEW

**Comment by stirby** [comment]
@mtojek I removed the `coder_parameter` test from `examples_test.go` since that test targets resources specifically. 

I find it interesting that the only two resources which don't generate code examples in the docs are prefixed with:

```hcl
provider "coder" {}
```

Since `coder_workspace_tags` is in the correct directory, the problem may be deeper than a pathing issue.

I couldn't find any errors in the output of `make gen`'s `tfplugindocs` call:

```
...
generating missing resource content
generating new template for "coder_app"
...
generating missing data source content
...
generating new template for data-source "coder_workspace_owner"
generating new template for data-source "coder_workspace_tags"
...
generating new template for data-source "coder_parameter"
generating missing function content
generating missing provider content
...
```

I also tried to add other resources to the `examples_test.go`, each of which failed. 

---

All this said, I would actually like to take a stab at rewriting the `examples_test.go`. My fear is that the tests only pass with inclusion of the provider, which prevents the docs from correctly generating.

Mind taking a look?

**Comment by stirby** [comment]
For now, lazily duplicated resource examples test loop for data sources to test.

**Comment by mtojek** [comment]
Alright, I think I made the CI happy now. `coder_parameter` and `coder_workspace_tags` are in `data-sources` now, and `examples_test.go` is validating them.

> I also tried to add other resources to the examples_test.go, each of which failed.

This may not be straightforward if examples depend on external fields or providers. For instance: `coder_agent_instance` uses `google_compute_instance` and we do not import `gcp` module.

**Review by mtojek — APPROVED** [review]
👍

**Pull request merged**
