### PR TITLE
docs: fix typo in built-in icons path

### PR DESCRIPTION
**Pull request by matifali**

### CODE REVIEW

**Comment by mafredri** [comment]
@matifali thanks for the PR! The markdown file is generated code, would you mind updating `app.go` as well?

**Comment by matifali** [comment]
I didn't notice that at first. I updated `app.go` also.

**Review by matifali — COMMENTED** [review]
done

**Review by mafredri — APPROVED** [review]

**Comment by mafredri** [comment]
Thanks @matifali 🎉!

**Pull request merged**
